### ISSUE TITLE
The code is in Tensorflow, not in PyTorch

### ISSUE THREAD

**Issue by HabibAouani** [rakhimovv/tcav#2]
Hello;

Everything is in the title.

Thank you
Habib

**Comment by rakhimovv** [comment]
Hi, @HabibAouani. Actually, this code was based on tf implementation, so unfortunately some things stayed from it but they are only related to the logging, reading some files.

Also, take a look at a [fork](https://github.com/myracheng/tcav) of this repo - it has a collab notebook inside it.

**Comment by HabibAouani** [comment]
Thank you very much !
