### ISSUE TITLE
Why there is cutted_model concept coming in models wrapper

### ISSUE THREAD

**Issue by avani17101** [rakhimovv/tcav#3]
Can you explain why there is ```cutted_model``` coming in models.py? Does it aggregate the activations of other layers? We only want to examine activations of ```bottleneck``` then what does  ```cutted_model``` do? I don't see such thing in tf implementation of TCAV and hence unable to understand.

@rakhimovv?

**Comment by avani17101** [comment]
I think I got it, we want the gradient of classID logit wrt activations in bottleneck layer.

**Comment by charchit7** [comment]
Hey @avani17101 could you please explain the logic you understood. I am not able to follow up.
